[package]
name = "fractic-env-config"
version = "0.1.0"
authors = ["Mart van Buren <mart@fractic.io>"]
edition = "2021"

[dependencies]
fractic-generic-server-error = { git = "https://github.com/fractic-io/rust-generic-server-error.git" }

[dev-dependencies]
once_cell = "1.19.0"
